<?xml version="1.0" encoding="utf-8"?><Database Name="Aisha_real" EntityNamespace="MainEntity.Models.Activity" Class="ActivityLogEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=dev.myvi.ru;Initial Catalog=Aisha_real;Persist Security Info=True;User ID=aisha" SettingsObjectName="MainEntity.Properties.Settings" SettingsPropertyName="Aisha_realConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ActivityLogXrefUsers" Member="ActivityLogXrefUsers">
    <Type Name="ActivityLogXrefUser">
      <Column Name="activityLogID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ActivityLog_ActivityLogXrefUser" Member="ActivityLog" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityLogType" Member="ActivityLogTypes">
    <Type Name="ActivityLogType">
      <Column Name="activityLogTypeID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="ActivityLogType_ActivityLog" Member="ActivityLogs" ThisKey="activityLogTypeID" OtherKey="activityLogTypeID" Type="ActivityLog" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityLogXrefEmail" Member="ActivityLogXrefEmails">
    <Type Name="ActivityLogXrefEmail">
      <Column Name="emailID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activityLogID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ActivityLog_ActivityLogXrefEmail" Member="ActivityLog" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLog" IsForeignKey="true" />
      <Association Name="Email_ActivityLogXrefEmail" Member="Email" ThisKey="emailID" OtherKey="emailID" Type="Email" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityLogXrefEntityItem" Member="ActivityLogXrefEntityItems">
    <Type Name="ActivityLogXrefEntityItem">
      <Column Name="activityLogID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ActivityLog_ActivityLogXrefEntityItem" Member="ActivityLog" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLog" IsForeignKey="true" />
      <Association Name="EntityItem_ActivityLogXrefEntityItem" Member="EntityItem" ThisKey="entityID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityLogXrefShopping" Member="ActivityLogXrefShoppings">
    <Type Name="ActivityLogXrefShopping">
      <Column Name="shoppingID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activityLogID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ActivityLog_ActivityLogXrefShopping" Member="ActivityLog" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityLog" Member="ActivityLogs">
    <Type Name="ActivityLog">
      <Column Name="activityLogID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="activityLogTypeID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="requestIP" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Association Name="ActivityLog_ActivityLogXrefUser" Member="ActivityLogXrefUsers" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLogXrefUser" />
      <Association Name="ActivityLog_ActivityLogXrefEmail" Member="ActivityLogXrefEmails" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLogXrefEmail" />
      <Association Name="ActivityLog_ActivityLogXrefEntityItem" Member="ActivityLogXrefEntityItems" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLogXrefEntityItem" />
      <Association Name="ActivityLog_ActivityLogXrefShopping" Member="ActivityLogXrefShoppings" ThisKey="activityLogID" OtherKey="activityLogID" Type="ActivityLogXrefShopping" />
      <Association Name="ActivityLogType_ActivityLog" Member="ActivityLogType" ThisKey="activityLogTypeID" OtherKey="activityLogTypeID" Type="ActivityLogType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Email" Member="Emails">
    <Type Name="Email">
      <Column Name="emailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Member="email1" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="Email_ActivityLogXrefEmail" Member="ActivityLogXrefEmails" ThisKey="emailID" OtherKey="emailID" Type="ActivityLogXrefEmail" />
    </Type>
  </Table>
  <Table Name="dbo.EntityItem" Member="EntityItems">
    <Type Name="EntityItem">
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rootEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="parentEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="creatorID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="hierarchiID" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="sortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EntityItem_ActivityLogXrefEntityItem" Member="ActivityLogXrefEntityItems" ThisKey="entityID" OtherKey="entityID" Type="ActivityLogXrefEntityItem" />
      <Association Name="EntityItem_ClassEntity" Member="ClassEntity" ThisKey="entityID" OtherKey="classID" Type="ClassEntity" Cardinality="One" />
      <Association Name="EntityItem_ProductEntity" Member="ProductEntity" ThisKey="entityID" OtherKey="productID" Type="ProductEntity" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.ClassEntity" Member="ClassEntities">
    <Type Name="ClassEntity">
      <Column Name="classID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="speakerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="duration" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="statDownloadCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statListenCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="newOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="EntityItem_ClassEntity" Member="EntityItem" ThisKey="classID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductEntity" Member="ProductEntities">
    <Type Name="ProductEntity">
      <Column Name="productID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="productTypeID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="price1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="price2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="EntityItem_ProductEntity" Member="EntityItem" ThisKey="productID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Membership" Member="Memberships">
    <Type Name="Membership">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activatedCart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="activationCartDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="freeOfferCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="refferedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="postalCode" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="postalAdderss" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="dayPhone" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="subscribeActivation" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>