#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEntity.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Aisha_real")]
	public partial class ClassEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEntityItem(MainEntity.Models.Catalog.EntityItem instance);
    partial void UpdateEntityItem(MainEntity.Models.Catalog.EntityItem instance);
    partial void DeleteEntityItem(MainEntity.Models.Catalog.EntityItem instance);
    partial void InsertTag(MainEntity.Models.Catalog.Tag instance);
    partial void UpdateTag(MainEntity.Models.Catalog.Tag instance);
    partial void DeleteTag(MainEntity.Models.Catalog.Tag instance);
    partial void InsertTagXrefEntity(MainEntity.Models.Catalog.TagXrefEntity instance);
    partial void UpdateTagXrefEntity(MainEntity.Models.Catalog.TagXrefEntity instance);
    partial void DeleteTagXrefEntity(MainEntity.Models.Catalog.TagXrefEntity instance);
    partial void InsertClassEntity(MainEntity.Models.Catalog.ClassEntity instance);
    partial void UpdateClassEntity(MainEntity.Models.Catalog.ClassEntity instance);
    partial void DeleteClassEntity(MainEntity.Models.Catalog.ClassEntity instance);
    partial void InsertCatalogItemXrefPortal(MainEntity.Models.Catalog.CatalogItemXrefPortal instance);
    partial void UpdateCatalogItemXrefPortal(MainEntity.Models.Catalog.CatalogItemXrefPortal instance);
    partial void DeleteCatalogItemXrefPortal(MainEntity.Models.Catalog.CatalogItemXrefPortal instance);
    partial void InsertProductEntity(MainEntity.Models.Catalog.ProductEntity instance);
    partial void UpdateProductEntity(MainEntity.Models.Catalog.ProductEntity instance);
    partial void DeleteProductEntity(MainEntity.Models.Catalog.ProductEntity instance);
    partial void InsertProductXrefEntity(MainEntity.Models.Catalog.ProductXrefEntity instance);
    partial void UpdateProductXrefEntity(MainEntity.Models.Catalog.ProductXrefEntity instance);
    partial void DeleteProductXrefEntity(MainEntity.Models.Catalog.ProductXrefEntity instance);
    partial void InsertCatalogItemExtend(MainEntity.Models.Catalog.CatalogItemExtend instance);
    partial void UpdateCatalogItemExtend(MainEntity.Models.Catalog.CatalogItemExtend instance);
    partial void DeleteCatalogItemExtend(MainEntity.Models.Catalog.CatalogItemExtend instance);
    partial void InsertSubscribePlanEntity(MainEntity.Models.Catalog.SubscribePlanEntity instance);
    partial void UpdateSubscribePlanEntity(MainEntity.Models.Catalog.SubscribePlanEntity instance);
    partial void DeleteSubscribePlanEntity(MainEntity.Models.Catalog.SubscribePlanEntity instance);
    partial void InsertSpeakerEntity(MainEntity.Models.Catalog.SpeakerEntity instance);
    partial void UpdateSpeakerEntity(MainEntity.Models.Catalog.SpeakerEntity instance);
    partial void DeleteSpeakerEntity(MainEntity.Models.Catalog.SpeakerEntity instance);
    partial void InsertProductEntityShipping(MainEntity.Models.Catalog.ProductEntityShipping instance);
    partial void UpdateProductEntityShipping(MainEntity.Models.Catalog.ProductEntityShipping instance);
    partial void DeleteProductEntityShipping(MainEntity.Models.Catalog.ProductEntityShipping instance);
    partial void InsertShippingLocation(MainEntity.Models.Catalog.ShippingLocation instance);
    partial void UpdateShippingLocation(MainEntity.Models.Catalog.ShippingLocation instance);
    partial void DeleteShippingLocation(MainEntity.Models.Catalog.ShippingLocation instance);
    partial void InsertFileEntity(MainEntity.Models.Catalog.FileEntity instance);
    partial void UpdateFileEntity(MainEntity.Models.Catalog.FileEntity instance);
    partial void DeleteFileEntity(MainEntity.Models.Catalog.FileEntity instance);
    partial void InsertSubscribePlanXref(MainEntity.Models.Catalog.SubscribePlanXref instance);
    partial void UpdateSubscribePlanXref(MainEntity.Models.Catalog.SubscribePlanXref instance);
    partial void DeleteSubscribePlanXref(MainEntity.Models.Catalog.SubscribePlanXref instance);
    #endregion
		
		public ClassEntityDataContext() : 
				base(global::MainEntity.Properties.Settings.Default.Aisha_realConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ClassEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClassEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClassEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClassEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.EntityItem> EntityItems
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.EntityItem>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.Tag> Tags
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.Tag>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.TagXrefEntity> TagXrefEntities
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.TagXrefEntity>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.ClassEntity> ClassEntities
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.ClassEntity>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.CatalogItemXrefPortal> CatalogItemXrefPortals
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.CatalogItemXrefPortal>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.ProductEntity> ProductEntities
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.ProductEntity>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.ProductXrefEntity> ProductXrefEntities
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.ProductXrefEntity>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.CatalogItemExtend> CatalogItemExtends
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.CatalogItemExtend>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.SubscribePlanEntity> SubscribePlanEntities
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.SubscribePlanEntity>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.vw_Category> vw_Categories
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.vw_Category>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.SpeakerEntity> SpeakerEntities
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.SpeakerEntity>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.ProductEntityShipping> ProductEntityShippings
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.ProductEntityShipping>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.ShippingLocation> ShippingLocations
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.ShippingLocation>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.FileEntity> FileEntities
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.FileEntity>();
			}
		}
		
		public System.Data.Linq.Table<MainEntity.Models.Catalog.SubscribePlanXref> SubscribePlanXrefs
		{
			get
			{
				return this.GetTable<MainEntity.Models.Catalog.SubscribePlanXref>();
			}
		}
	}
}
namespace MainEntity.Models.Catalog
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EntityItem")]
	public partial class EntityItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _entityID;
		
		private long _rootEntityID;
		
		private long _parentEntityID;
		
		private int _typeID;
		
		private System.Guid _creatorID;
		
		private string _hierarchiID;
		
		private string _title;
		
		private int _sortOrder;
		
		private System.DateTime _createDate;
		
		private bool _deleted;
		
		private bool _active;
		
		private EntitySet<TagXrefEntity> _TagXrefEntities;
		
		private EntitySet<ClassEntity> _SpeakerClassEntities;
		
		private EntityRef<ClassEntity> _ClassEntity;
		
		private EntitySet<ClassEntity> _ClassEntities;
		
		private EntitySet<CatalogItemXrefPortal> _CatalogItemXrefPortals;
		
		private EntityRef<ProductEntity> _ProductEntity;
		
		private EntitySet<ProductXrefEntity> _ProductXrefEntities;
		
		private EntityRef<CatalogItemExtend> _CatalogItemExtend;
		
		private EntityRef<SubscribePlanEntity> _SubscribePlanEntity;
		
		private EntityRef<SpeakerEntity> _SpeakerEntity;
		
		private EntityRef<FileEntity> _FileEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnentityIDChanging(long value);
    partial void OnentityIDChanged();
    partial void OnrootEntityIDChanging(long value);
    partial void OnrootEntityIDChanged();
    partial void OnparentEntityIDChanging(long value);
    partial void OnparentEntityIDChanged();
    partial void OntypeIDChanging(int value);
    partial void OntypeIDChanged();
    partial void OncreatorIDChanging(System.Guid value);
    partial void OncreatorIDChanged();
    partial void OnhierarchiIDChanging(string value);
    partial void OnhierarchiIDChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnsortOrderChanging(int value);
    partial void OnsortOrderChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OndeletedChanging(bool value);
    partial void OndeletedChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    #endregion
		
		public EntityItem()
		{
			this._TagXrefEntities = new EntitySet<TagXrefEntity>(new Action<TagXrefEntity>(this.attach_TagXrefEntities), new Action<TagXrefEntity>(this.detach_TagXrefEntities));
			this._SpeakerClassEntities = new EntitySet<ClassEntity>(new Action<ClassEntity>(this.attach_SpeakerClassEntities), new Action<ClassEntity>(this.detach_SpeakerClassEntities));
			this._ClassEntity = default(EntityRef<ClassEntity>);
			this._ClassEntities = new EntitySet<ClassEntity>(new Action<ClassEntity>(this.attach_ClassEntities), new Action<ClassEntity>(this.detach_ClassEntities));
			this._CatalogItemXrefPortals = new EntitySet<CatalogItemXrefPortal>(new Action<CatalogItemXrefPortal>(this.attach_CatalogItemXrefPortals), new Action<CatalogItemXrefPortal>(this.detach_CatalogItemXrefPortals));
			this._ProductEntity = default(EntityRef<ProductEntity>);
			this._ProductXrefEntities = new EntitySet<ProductXrefEntity>(new Action<ProductXrefEntity>(this.attach_ProductXrefEntities), new Action<ProductXrefEntity>(this.detach_ProductXrefEntities));
			this._CatalogItemExtend = default(EntityRef<CatalogItemExtend>);
			this._SubscribePlanEntity = default(EntityRef<SubscribePlanEntity>);
			this._SpeakerEntity = default(EntityRef<SpeakerEntity>);
			this._FileEntity = default(EntityRef<FileEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entityID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long entityID
		{
			get
			{
				return this._entityID;
			}
			set
			{
				if ((this._entityID != value))
				{
					this.OnentityIDChanging(value);
					this.SendPropertyChanging();
					this._entityID = value;
					this.SendPropertyChanged("entityID");
					this.OnentityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rootEntityID", DbType="BigInt NOT NULL")]
		public long rootEntityID
		{
			get
			{
				return this._rootEntityID;
			}
			set
			{
				if ((this._rootEntityID != value))
				{
					this.OnrootEntityIDChanging(value);
					this.SendPropertyChanging();
					this._rootEntityID = value;
					this.SendPropertyChanged("rootEntityID");
					this.OnrootEntityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentEntityID", DbType="BigInt NOT NULL")]
		public long parentEntityID
		{
			get
			{
				return this._parentEntityID;
			}
			set
			{
				if ((this._parentEntityID != value))
				{
					this.OnparentEntityIDChanging(value);
					this.SendPropertyChanging();
					this._parentEntityID = value;
					this.SendPropertyChanged("parentEntityID");
					this.OnparentEntityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeID", DbType="Int NOT NULL")]
		public int typeID
		{
			get
			{
				return this._typeID;
			}
			set
			{
				if ((this._typeID != value))
				{
					this.OntypeIDChanging(value);
					this.SendPropertyChanging();
					this._typeID = value;
					this.SendPropertyChanged("typeID");
					this.OntypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creatorID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid creatorID
		{
			get
			{
				return this._creatorID;
			}
			set
			{
				if ((this._creatorID != value))
				{
					this.OncreatorIDChanging(value);
					this.SendPropertyChanging();
					this._creatorID = value;
					this.SendPropertyChanged("creatorID");
					this.OncreatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hierarchiID", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string hierarchiID
		{
			get
			{
				return this._hierarchiID;
			}
			set
			{
				if ((this._hierarchiID != value))
				{
					this.OnhierarchiIDChanging(value);
					this.SendPropertyChanging();
					this._hierarchiID = value;
					this.SendPropertyChanged("hierarchiID");
					this.OnhierarchiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(512) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sortOrder", DbType="Int NOT NULL")]
		public int sortOrder
		{
			get
			{
				return this._sortOrder;
			}
			set
			{
				if ((this._sortOrder != value))
				{
					this.OnsortOrderChanging(value);
					this.SendPropertyChanging();
					this._sortOrder = value;
					this.SendPropertyChanged("sortOrder");
					this.OnsortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit NOT NULL")]
		public bool deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_TagXrefEntity", Storage="_TagXrefEntities", ThisKey="entityID", OtherKey="entityID")]
		public EntitySet<TagXrefEntity> TagXrefEntities
		{
			get
			{
				return this._TagXrefEntities;
			}
			set
			{
				this._TagXrefEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ClassEntity", Storage="_SpeakerClassEntities", ThisKey="entityID", OtherKey="speakerID")]
		public EntitySet<ClassEntity> SpeakerClassEntities
		{
			get
			{
				return this._SpeakerClassEntities;
			}
			set
			{
				this._SpeakerClassEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ClassEntity1", Storage="_ClassEntity", ThisKey="entityID", OtherKey="classID", IsUnique=true, IsForeignKey=false)]
		public ClassEntity ClassEntity
		{
			get
			{
				return this._ClassEntity.Entity;
			}
			set
			{
				ClassEntity previousValue = this._ClassEntity.Entity;
				if (((previousValue != value) 
							|| (this._ClassEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClassEntity.Entity = null;
						previousValue.EntityItem = null;
					}
					this._ClassEntity.Entity = value;
					if ((value != null))
					{
						value.EntityItem = this;
					}
					this.SendPropertyChanged("ClassEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ClassEntity2", Storage="_ClassEntities", ThisKey="parentEntityID", OtherKey="classID")]
		public EntitySet<ClassEntity> ClassEntities
		{
			get
			{
				return this._ClassEntities;
			}
			set
			{
				this._ClassEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_CatalogItemXrefPortal", Storage="_CatalogItemXrefPortals", ThisKey="entityID", OtherKey="catalogItemID")]
		public EntitySet<CatalogItemXrefPortal> CatalogItemXrefPortals
		{
			get
			{
				return this._CatalogItemXrefPortals;
			}
			set
			{
				this._CatalogItemXrefPortals.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ProductEntity", Storage="_ProductEntity", ThisKey="entityID", OtherKey="productID", IsUnique=true, IsForeignKey=false)]
		public ProductEntity ProductEntity
		{
			get
			{
				return this._ProductEntity.Entity;
			}
			set
			{
				ProductEntity previousValue = this._ProductEntity.Entity;
				if (((previousValue != value) 
							|| (this._ProductEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductEntity.Entity = null;
						previousValue.EntityItem = null;
					}
					this._ProductEntity.Entity = value;
					if ((value != null))
					{
						value.EntityItem = this;
					}
					this.SendPropertyChanged("ProductEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ProductXrefEntity", Storage="_ProductXrefEntities", ThisKey="entityID", OtherKey="entityID")]
		public EntitySet<ProductXrefEntity> ProductXrefEntities
		{
			get
			{
				return this._ProductXrefEntities;
			}
			set
			{
				this._ProductXrefEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_CatalogItemExtend", Storage="_CatalogItemExtend", ThisKey="entityID", OtherKey="entityID", IsUnique=true, IsForeignKey=false)]
		public CatalogItemExtend CatalogItemExtend
		{
			get
			{
				return this._CatalogItemExtend.Entity;
			}
			set
			{
				CatalogItemExtend previousValue = this._CatalogItemExtend.Entity;
				if (((previousValue != value) 
							|| (this._CatalogItemExtend.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CatalogItemExtend.Entity = null;
						previousValue.EntityItem = null;
					}
					this._CatalogItemExtend.Entity = value;
					if ((value != null))
					{
						value.EntityItem = this;
					}
					this.SendPropertyChanged("CatalogItemExtend");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_SubscribePlanEntity", Storage="_SubscribePlanEntity", ThisKey="entityID", OtherKey="subscribePlanID", IsUnique=true, IsForeignKey=false)]
		public SubscribePlanEntity SubscribePlanEntity
		{
			get
			{
				return this._SubscribePlanEntity.Entity;
			}
			set
			{
				SubscribePlanEntity previousValue = this._SubscribePlanEntity.Entity;
				if (((previousValue != value) 
							|| (this._SubscribePlanEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SubscribePlanEntity.Entity = null;
						previousValue.EntityItem = null;
					}
					this._SubscribePlanEntity.Entity = value;
					if ((value != null))
					{
						value.EntityItem = this;
					}
					this.SendPropertyChanged("SubscribePlanEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_SpeakerEntity", Storage="_SpeakerEntity", ThisKey="entityID", OtherKey="speakerID", IsUnique=true, IsForeignKey=false)]
		public SpeakerEntity SpeakerEntity
		{
			get
			{
				return this._SpeakerEntity.Entity;
			}
			set
			{
				SpeakerEntity previousValue = this._SpeakerEntity.Entity;
				if (((previousValue != value) 
							|| (this._SpeakerEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SpeakerEntity.Entity = null;
						previousValue.EntityItem = null;
					}
					this._SpeakerEntity.Entity = value;
					if ((value != null))
					{
						value.EntityItem = this;
					}
					this.SendPropertyChanged("SpeakerEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_FileEntity", Storage="_FileEntity", ThisKey="entityID", OtherKey="fileID", IsUnique=true, IsForeignKey=false)]
		public FileEntity FileEntity
		{
			get
			{
				return this._FileEntity.Entity;
			}
			set
			{
				FileEntity previousValue = this._FileEntity.Entity;
				if (((previousValue != value) 
							|| (this._FileEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FileEntity.Entity = null;
						previousValue.EntityItem = null;
					}
					this._FileEntity.Entity = value;
					if ((value != null))
					{
						value.EntityItem = this;
					}
					this.SendPropertyChanged("FileEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TagXrefEntities(TagXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.EntityItem = this;
		}
		
		private void detach_TagXrefEntities(TagXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.EntityItem = null;
		}
		
		private void attach_SpeakerClassEntities(ClassEntity entity)
		{
			this.SendPropertyChanging();
			entity.SpeakerEntityItem = this;
		}
		
		private void detach_SpeakerClassEntities(ClassEntity entity)
		{
			this.SendPropertyChanging();
			entity.SpeakerEntityItem = null;
		}
		
		private void attach_ClassEntities(ClassEntity entity)
		{
			this.SendPropertyChanging();
			entity.ParentClassEntity = this;
		}
		
		private void detach_ClassEntities(ClassEntity entity)
		{
			this.SendPropertyChanging();
			entity.ParentClassEntity = null;
		}
		
		private void attach_CatalogItemXrefPortals(CatalogItemXrefPortal entity)
		{
			this.SendPropertyChanging();
			entity.EntityItem = this;
		}
		
		private void detach_CatalogItemXrefPortals(CatalogItemXrefPortal entity)
		{
			this.SendPropertyChanging();
			entity.EntityItem = null;
		}
		
		private void attach_ProductXrefEntities(ProductXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.EntityItem = this;
		}
		
		private void detach_ProductXrefEntities(ProductXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.EntityItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tags")]
	public partial class Tag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tagID;
		
		private short _tagTypeID;
		
		private string _name;
		
		private EntitySet<TagXrefEntity> _TagXrefEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntagIDChanging(int value);
    partial void OntagIDChanged();
    partial void OntagTypeIDChanging(short value);
    partial void OntagTypeIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Tag()
		{
			this._TagXrefEntities = new EntitySet<TagXrefEntity>(new Action<TagXrefEntity>(this.attach_TagXrefEntities), new Action<TagXrefEntity>(this.detach_TagXrefEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tagID
		{
			get
			{
				return this._tagID;
			}
			set
			{
				if ((this._tagID != value))
				{
					this.OntagIDChanging(value);
					this.SendPropertyChanging();
					this._tagID = value;
					this.SendPropertyChanged("tagID");
					this.OntagIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagTypeID", DbType="SmallInt NOT NULL")]
		public short tagTypeID
		{
			get
			{
				return this._tagTypeID;
			}
			set
			{
				if ((this._tagTypeID != value))
				{
					this.OntagTypeIDChanging(value);
					this.SendPropertyChanging();
					this._tagTypeID = value;
					this.SendPropertyChanged("tagTypeID");
					this.OntagTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tag_TagXrefEntity", Storage="_TagXrefEntities", ThisKey="tagID", OtherKey="tagID")]
		public EntitySet<TagXrefEntity> TagXrefEntities
		{
			get
			{
				return this._TagXrefEntities;
			}
			set
			{
				this._TagXrefEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TagXrefEntities(TagXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.Tag = this;
		}
		
		private void detach_TagXrefEntities(TagXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.Tag = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TagXrefEntity")]
	public partial class TagXrefEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tagID;
		
		private long _entityID;
		
		private EntityRef<EntityItem> _EntityItem;
		
		private EntityRef<Tag> _Tag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntagIDChanging(int value);
    partial void OntagIDChanged();
    partial void OnentityIDChanging(long value);
    partial void OnentityIDChanged();
    #endregion
		
		public TagXrefEntity()
		{
			this._EntityItem = default(EntityRef<EntityItem>);
			this._Tag = default(EntityRef<Tag>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int tagID
		{
			get
			{
				return this._tagID;
			}
			set
			{
				if ((this._tagID != value))
				{
					if (this._Tag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntagIDChanging(value);
					this.SendPropertyChanging();
					this._tagID = value;
					this.SendPropertyChanged("tagID");
					this.OntagIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entityID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long entityID
		{
			get
			{
				return this._entityID;
			}
			set
			{
				if ((this._entityID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnentityIDChanging(value);
					this.SendPropertyChanging();
					this._entityID = value;
					this.SendPropertyChanged("entityID");
					this.OnentityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_TagXrefEntity", Storage="_EntityItem", ThisKey="entityID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.TagXrefEntities.Remove(this);
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.TagXrefEntities.Add(this);
						this._entityID = value.entityID;
					}
					else
					{
						this._entityID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tag_TagXrefEntity", Storage="_Tag", ThisKey="tagID", OtherKey="tagID", IsForeignKey=true)]
		public Tag Tag
		{
			get
			{
				return this._Tag.Entity;
			}
			set
			{
				Tag previousValue = this._Tag.Entity;
				if (((previousValue != value) 
							|| (this._Tag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tag.Entity = null;
						previousValue.TagXrefEntities.Remove(this);
					}
					this._Tag.Entity = value;
					if ((value != null))
					{
						value.TagXrefEntities.Add(this);
						this._tagID = value.tagID;
					}
					else
					{
						this._tagID = default(int);
					}
					this.SendPropertyChanged("Tag");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClassEntity")]
	public partial class ClassEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _classID;
		
		private long _speakerID;
		
		private string _description;
		
		private System.Nullable<System.TimeSpan> _duration;
		
		private System.Nullable<int> _newOrder;
		
		private EntityRef<EntityItem> _SpeakerEntityItem;
		
		private EntityRef<EntityItem> _EntityItem;
		
		private EntityRef<SpeakerEntity> _SpeakerEntity;
		
		private EntityRef<EntityItem> _ParentClassEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassIDChanging(long value);
    partial void OnclassIDChanged();
    partial void OnspeakerIDChanging(long value);
    partial void OnspeakerIDChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OndurationChanging(System.Nullable<System.TimeSpan> value);
    partial void OndurationChanged();
    partial void OnnewOrderChanging(System.Nullable<int> value);
    partial void OnnewOrderChanged();
    #endregion
		
		public ClassEntity()
		{
			this._SpeakerEntityItem = default(EntityRef<EntityItem>);
			this._EntityItem = default(EntityRef<EntityItem>);
			this._SpeakerEntity = default(EntityRef<SpeakerEntity>);
			this._ParentClassEntity = default(EntityRef<EntityItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long classID
		{
			get
			{
				return this._classID;
			}
			set
			{
				if ((this._classID != value))
				{
					if ((this._EntityItem.HasLoadedOrAssignedValue || this._ParentClassEntity.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclassIDChanging(value);
					this.SendPropertyChanging();
					this._classID = value;
					this.SendPropertyChanged("classID");
					this.OnclassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speakerID", DbType="BigInt NOT NULL")]
		public long speakerID
		{
			get
			{
				return this._speakerID;
			}
			set
			{
				if ((this._speakerID != value))
				{
					if ((this._SpeakerEntityItem.HasLoadedOrAssignedValue || this._SpeakerEntity.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnspeakerIDChanging(value);
					this.SendPropertyChanging();
					this._speakerID = value;
					this.SendPropertyChanged("speakerID");
					this.OnspeakerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Time")]
		public System.Nullable<System.TimeSpan> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newOrder", DbType="Int")]
		public System.Nullable<int> newOrder
		{
			get
			{
				return this._newOrder;
			}
			set
			{
				if ((this._newOrder != value))
				{
					this.OnnewOrderChanging(value);
					this.SendPropertyChanging();
					this._newOrder = value;
					this.SendPropertyChanged("newOrder");
					this.OnnewOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ClassEntity", Storage="_SpeakerEntityItem", ThisKey="speakerID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem SpeakerEntityItem
		{
			get
			{
				return this._SpeakerEntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._SpeakerEntityItem.Entity;
				if (((previousValue != value) 
							|| (this._SpeakerEntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SpeakerEntityItem.Entity = null;
						previousValue.SpeakerClassEntities.Remove(this);
					}
					this._SpeakerEntityItem.Entity = value;
					if ((value != null))
					{
						value.SpeakerClassEntities.Add(this);
						this._speakerID = value.entityID;
					}
					else
					{
						this._speakerID = default(long);
					}
					this.SendPropertyChanged("SpeakerEntityItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ClassEntity1", Storage="_EntityItem", ThisKey="classID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.ClassEntity = null;
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.ClassEntity = this;
						this._classID = value.entityID;
					}
					else
					{
						this._classID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SpeakerEntity_ClassEntity", Storage="_SpeakerEntity", ThisKey="speakerID", OtherKey="speakerID", IsForeignKey=true)]
		public SpeakerEntity SpeakerEntity
		{
			get
			{
				return this._SpeakerEntity.Entity;
			}
			set
			{
				SpeakerEntity previousValue = this._SpeakerEntity.Entity;
				if (((previousValue != value) 
							|| (this._SpeakerEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SpeakerEntity.Entity = null;
						previousValue.ClassEntities.Remove(this);
					}
					this._SpeakerEntity.Entity = value;
					if ((value != null))
					{
						value.ClassEntities.Add(this);
						this._speakerID = value.speakerID;
					}
					else
					{
						this._speakerID = default(long);
					}
					this.SendPropertyChanged("SpeakerEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ClassEntity2", Storage="_ParentClassEntity", ThisKey="classID", OtherKey="parentEntityID", IsForeignKey=true)]
		public EntityItem ParentClassEntity
		{
			get
			{
				return this._ParentClassEntity.Entity;
			}
			set
			{
				EntityItem previousValue = this._ParentClassEntity.Entity;
				if (((previousValue != value) 
							|| (this._ParentClassEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ParentClassEntity.Entity = null;
						previousValue.ClassEntities.Remove(this);
					}
					this._ParentClassEntity.Entity = value;
					if ((value != null))
					{
						value.ClassEntities.Add(this);
						this._classID = value.parentEntityID;
					}
					else
					{
						this._classID = default(long);
					}
					this.SendPropertyChanged("ParentClassEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatalogItemXrefPortal")]
	public partial class CatalogItemXrefPortal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _portalID;
		
		private long _catalogItemID;
		
		private bool _isVisible;
		
		private bool _isFree;
		
		private bool _isFreeOffer;
		
		private bool _isFullFree;
		
		private EntityRef<EntityItem> _EntityItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnportalIDChanging(long value);
    partial void OnportalIDChanged();
    partial void OncatalogItemIDChanging(long value);
    partial void OncatalogItemIDChanged();
    partial void OnisVisibleChanging(bool value);
    partial void OnisVisibleChanged();
    partial void OnisFreeChanging(bool value);
    partial void OnisFreeChanged();
    partial void OnisFreeOfferChanging(bool value);
    partial void OnisFreeOfferChanged();
    partial void OnisFullFreeChanging(bool value);
    partial void OnisFullFreeChanged();
    #endregion
		
		public CatalogItemXrefPortal()
		{
			this._EntityItem = default(EntityRef<EntityItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portalID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long portalID
		{
			get
			{
				return this._portalID;
			}
			set
			{
				if ((this._portalID != value))
				{
					this.OnportalIDChanging(value);
					this.SendPropertyChanging();
					this._portalID = value;
					this.SendPropertyChanged("portalID");
					this.OnportalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catalogItemID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long catalogItemID
		{
			get
			{
				return this._catalogItemID;
			}
			set
			{
				if ((this._catalogItemID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncatalogItemIDChanging(value);
					this.SendPropertyChanging();
					this._catalogItemID = value;
					this.SendPropertyChanged("catalogItemID");
					this.OncatalogItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isVisible", DbType="Bit NOT NULL")]
		public bool isVisible
		{
			get
			{
				return this._isVisible;
			}
			set
			{
				if ((this._isVisible != value))
				{
					this.OnisVisibleChanging(value);
					this.SendPropertyChanging();
					this._isVisible = value;
					this.SendPropertyChanged("isVisible");
					this.OnisVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFree", DbType="Bit NOT NULL")]
		public bool isFree
		{
			get
			{
				return this._isFree;
			}
			set
			{
				if ((this._isFree != value))
				{
					this.OnisFreeChanging(value);
					this.SendPropertyChanging();
					this._isFree = value;
					this.SendPropertyChanged("isFree");
					this.OnisFreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFreeOffer", DbType="Bit NOT NULL")]
		public bool isFreeOffer
		{
			get
			{
				return this._isFreeOffer;
			}
			set
			{
				if ((this._isFreeOffer != value))
				{
					this.OnisFreeOfferChanging(value);
					this.SendPropertyChanging();
					this._isFreeOffer = value;
					this.SendPropertyChanged("isFreeOffer");
					this.OnisFreeOfferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFullFree", DbType="Bit NOT NULL")]
		public bool isFullFree
		{
			get
			{
				return this._isFullFree;
			}
			set
			{
				if ((this._isFullFree != value))
				{
					this.OnisFullFreeChanging(value);
					this.SendPropertyChanging();
					this._isFullFree = value;
					this.SendPropertyChanged("isFullFree");
					this.OnisFullFreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_CatalogItemXrefPortal", Storage="_EntityItem", ThisKey="catalogItemID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.CatalogItemXrefPortals.Remove(this);
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.CatalogItemXrefPortals.Add(this);
						this._catalogItemID = value.entityID;
					}
					else
					{
						this._catalogItemID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductEntity")]
	public partial class ProductEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _productID;
		
		private short _productTypeID;
		
		private System.Nullable<decimal> _price1;
		
		private System.Nullable<decimal> _price2;
		
		private string _description;
		
		private bool _unlimitedAccessInLibrary;
		
		private EntitySet<ProductXrefEntity> _ProductXrefEntities;
		
		private EntityRef<ProductEntityShipping> _ProductEntityShipping;
		
		private EntityRef<EntityItem> _EntityItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIDChanging(long value);
    partial void OnproductIDChanged();
    partial void OnproductTypeIDChanging(short value);
    partial void OnproductTypeIDChanged();
    partial void Onprice1Changing(System.Nullable<decimal> value);
    partial void Onprice1Changed();
    partial void Onprice2Changing(System.Nullable<decimal> value);
    partial void Onprice2Changed();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnunlimitedAccessInLibraryChanging(bool value);
    partial void OnunlimitedAccessInLibraryChanged();
    #endregion
		
		public ProductEntity()
		{
			this._ProductXrefEntities = new EntitySet<ProductXrefEntity>(new Action<ProductXrefEntity>(this.attach_ProductXrefEntities), new Action<ProductXrefEntity>(this.detach_ProductXrefEntities));
			this._ProductEntityShipping = default(EntityRef<ProductEntityShipping>);
			this._EntityItem = default(EntityRef<EntityItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productTypeID", DbType="SmallInt NOT NULL")]
		public short productTypeID
		{
			get
			{
				return this._productTypeID;
			}
			set
			{
				if ((this._productTypeID != value))
				{
					this.OnproductTypeIDChanging(value);
					this.SendPropertyChanging();
					this._productTypeID = value;
					this.SendPropertyChanged("productTypeID");
					this.OnproductTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price1", DbType="Money")]
		public System.Nullable<decimal> price1
		{
			get
			{
				return this._price1;
			}
			set
			{
				if ((this._price1 != value))
				{
					this.Onprice1Changing(value);
					this.SendPropertyChanging();
					this._price1 = value;
					this.SendPropertyChanged("price1");
					this.Onprice1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price2", DbType="Money")]
		public System.Nullable<decimal> price2
		{
			get
			{
				return this._price2;
			}
			set
			{
				if ((this._price2 != value))
				{
					this.Onprice2Changing(value);
					this.SendPropertyChanging();
					this._price2 = value;
					this.SendPropertyChanged("price2");
					this.Onprice2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unlimitedAccessInLibrary", DbType="Bit NO NULL")]
		public bool unlimitedAccessInLibrary
		{
			get
			{
				return this._unlimitedAccessInLibrary;
			}
			set
			{
				if ((this._unlimitedAccessInLibrary != value))
				{
					this.OnunlimitedAccessInLibraryChanging(value);
					this.SendPropertyChanging();
					this._unlimitedAccessInLibrary = value;
					this.SendPropertyChanged("unlimitedAccessInLibrary");
					this.OnunlimitedAccessInLibraryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductEntity_ProductXrefEntity", Storage="_ProductXrefEntities", ThisKey="productID", OtherKey="productID")]
		public EntitySet<ProductXrefEntity> ProductXrefEntities
		{
			get
			{
				return this._ProductXrefEntities;
			}
			set
			{
				this._ProductXrefEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductEntity_ProductEntityShipping", Storage="_ProductEntityShipping", ThisKey="productID", OtherKey="productID", IsUnique=true, IsForeignKey=false)]
		public ProductEntityShipping ProductEntityShipping
		{
			get
			{
				return this._ProductEntityShipping.Entity;
			}
			set
			{
				ProductEntityShipping previousValue = this._ProductEntityShipping.Entity;
				if (((previousValue != value) 
							|| (this._ProductEntityShipping.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductEntityShipping.Entity = null;
						previousValue.ProductEntity = null;
					}
					this._ProductEntityShipping.Entity = value;
					if ((value != null))
					{
						value.ProductEntity = this;
					}
					this.SendPropertyChanged("ProductEntityShipping");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ProductEntity", Storage="_EntityItem", ThisKey="productID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.ProductEntity = null;
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.ProductEntity = this;
						this._productID = value.entityID;
					}
					else
					{
						this._productID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProductXrefEntities(ProductXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.ProductEntity = this;
		}
		
		private void detach_ProductXrefEntities(ProductXrefEntity entity)
		{
			this.SendPropertyChanging();
			entity.ProductEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductXrefEntity")]
	public partial class ProductXrefEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _productID;
		
		private long _entityID;
		
		private EntityRef<EntityItem> _EntityItem;
		
		private EntityRef<ProductEntity> _ProductEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIDChanging(long value);
    partial void OnproductIDChanged();
    partial void OnentityIDChanging(long value);
    partial void OnentityIDChanged();
    #endregion
		
		public ProductXrefEntity()
		{
			this._EntityItem = default(EntityRef<EntityItem>);
			this._ProductEntity = default(EntityRef<ProductEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					if (this._ProductEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entityID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long entityID
		{
			get
			{
				return this._entityID;
			}
			set
			{
				if ((this._entityID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnentityIDChanging(value);
					this.SendPropertyChanging();
					this._entityID = value;
					this.SendPropertyChanged("entityID");
					this.OnentityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_ProductXrefEntity", Storage="_EntityItem", ThisKey="entityID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.ProductXrefEntities.Remove(this);
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.ProductXrefEntities.Add(this);
						this._entityID = value.entityID;
					}
					else
					{
						this._entityID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductEntity_ProductXrefEntity", Storage="_ProductEntity", ThisKey="productID", OtherKey="productID", IsForeignKey=true)]
		public ProductEntity ProductEntity
		{
			get
			{
				return this._ProductEntity.Entity;
			}
			set
			{
				ProductEntity previousValue = this._ProductEntity.Entity;
				if (((previousValue != value) 
							|| (this._ProductEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductEntity.Entity = null;
						previousValue.ProductXrefEntities.Remove(this);
					}
					this._ProductEntity.Entity = value;
					if ((value != null))
					{
						value.ProductXrefEntities.Add(this);
						this._productID = value.productID;
					}
					else
					{
						this._productID = default(long);
					}
					this.SendPropertyChanged("ProductEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatalogItemExtend")]
	public partial class CatalogItemExtend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _entityID;
		
		private string _code;
		
		private string _notes;
		
		private EntityRef<EntityItem> _EntityItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnentityIDChanging(long value);
    partial void OnentityIDChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    #endregion
		
		public CatalogItemExtend()
		{
			this._EntityItem = default(EntityRef<EntityItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entityID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long entityID
		{
			get
			{
				return this._entityID;
			}
			set
			{
				if ((this._entityID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnentityIDChanging(value);
					this.SendPropertyChanging();
					this._entityID = value;
					this.SendPropertyChanged("entityID");
					this.OnentityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(128)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_CatalogItemExtend", Storage="_EntityItem", ThisKey="entityID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.CatalogItemExtend = null;
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.CatalogItemExtend = this;
						this._entityID = value.entityID;
					}
					else
					{
						this._entityID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubscribePlanEntity")]
	public partial class SubscribePlanEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _subscribePlanID;
		
		private short _durationInDays;
		
		private short _durationInMonths;
		
		private int _freeUnitsOnSubscribe;
		
		private int _freeOfferCnt;
		
		private string _description;
		
		private EntitySet<SubscribePlanXref> _SubscribePlanXrefs;
		
		private EntityRef<SubscribePlanXref> _SubscribePlanXref;
		
		private EntityRef<EntityItem> _EntityItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsubscribePlanIDChanging(long value);
    partial void OnsubscribePlanIDChanged();
    partial void OndurationInDaysChanging(short value);
    partial void OndurationInDaysChanged();
    partial void OndurationInMonthsChanging(short value);
    partial void OndurationInMonthsChanged();
    partial void OnfreeUnitsOnSubscribeChanging(int value);
    partial void OnfreeUnitsOnSubscribeChanged();
    partial void OnfreeOfferCntChanging(int value);
    partial void OnfreeOfferCntChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public SubscribePlanEntity()
		{
			this._SubscribePlanXrefs = new EntitySet<SubscribePlanXref>(new Action<SubscribePlanXref>(this.attach_SubscribePlanXrefs), new Action<SubscribePlanXref>(this.detach_SubscribePlanXrefs));
			this._SubscribePlanXref = default(EntityRef<SubscribePlanXref>);
			this._EntityItem = default(EntityRef<EntityItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subscribePlanID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long subscribePlanID
		{
			get
			{
				return this._subscribePlanID;
			}
			set
			{
				if ((this._subscribePlanID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsubscribePlanIDChanging(value);
					this.SendPropertyChanging();
					this._subscribePlanID = value;
					this.SendPropertyChanged("subscribePlanID");
					this.OnsubscribePlanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durationInDays", DbType="SmallInt NOT NULL")]
		public short durationInDays
		{
			get
			{
				return this._durationInDays;
			}
			set
			{
				if ((this._durationInDays != value))
				{
					this.OndurationInDaysChanging(value);
					this.SendPropertyChanging();
					this._durationInDays = value;
					this.SendPropertyChanged("durationInDays");
					this.OndurationInDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durationInMonths", DbType="SmallInt NOT NULL")]
		public short durationInMonths
		{
			get
			{
				return this._durationInMonths;
			}
			set
			{
				if ((this._durationInMonths != value))
				{
					this.OndurationInMonthsChanging(value);
					this.SendPropertyChanging();
					this._durationInMonths = value;
					this.SendPropertyChanged("durationInMonths");
					this.OndurationInMonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeUnitsOnSubscribe", DbType="Int NOT NULL")]
		public int freeUnitsOnSubscribe
		{
			get
			{
				return this._freeUnitsOnSubscribe;
			}
			set
			{
				if ((this._freeUnitsOnSubscribe != value))
				{
					this.OnfreeUnitsOnSubscribeChanging(value);
					this.SendPropertyChanging();
					this._freeUnitsOnSubscribe = value;
					this.SendPropertyChanged("freeUnitsOnSubscribe");
					this.OnfreeUnitsOnSubscribeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeOfferCnt", DbType="Int NOT NULL")]
		public int freeOfferCnt
		{
			get
			{
				return this._freeOfferCnt;
			}
			set
			{
				if ((this._freeOfferCnt != value))
				{
					this.OnfreeOfferCntChanging(value);
					this.SendPropertyChanging();
					this._freeOfferCnt = value;
					this.SendPropertyChanged("freeOfferCnt");
					this.OnfreeOfferCntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(1024)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubscribePlanEntity_SubscribePlanXref", Storage="_SubscribePlanXrefs", ThisKey="subscribePlanID", OtherKey="nextSubscribePlanID")]
		public EntitySet<SubscribePlanXref> SubscribePlanXrefs
		{
			get
			{
				return this._SubscribePlanXrefs;
			}
			set
			{
				this._SubscribePlanXrefs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubscribePlanEntity_SubscribePlanXref1", Storage="_SubscribePlanXref", ThisKey="subscribePlanID", OtherKey="subscribePlanID", IsUnique=true, IsForeignKey=false)]
		public SubscribePlanXref SubscribePlanXref
		{
			get
			{
				return this._SubscribePlanXref.Entity;
			}
			set
			{
				SubscribePlanXref previousValue = this._SubscribePlanXref.Entity;
				if (((previousValue != value) 
							|| (this._SubscribePlanXref.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SubscribePlanXref.Entity = null;
						previousValue.SubscribePlanEntity1 = null;
					}
					this._SubscribePlanXref.Entity = value;
					if ((value != null))
					{
						value.SubscribePlanEntity1 = this;
					}
					this.SendPropertyChanged("SubscribePlanXref");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_SubscribePlanEntity", Storage="_EntityItem", ThisKey="subscribePlanID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.SubscribePlanEntity = null;
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.SubscribePlanEntity = this;
						this._subscribePlanID = value.entityID;
					}
					else
					{
						this._subscribePlanID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubscribePlanXrefs(SubscribePlanXref entity)
		{
			this.SendPropertyChanging();
			entity.SubscribePlanEntity = this;
		}
		
		private void detach_SubscribePlanXrefs(SubscribePlanXref entity)
		{
			this.SendPropertyChanging();
			entity.SubscribePlanEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Category")]
	public partial class vw_Category
	{
		
		private int _tagID;
		
		private string _name;
		
		private System.Nullable<int> _count;
		
		public vw_Category()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int tagID
		{
			get
			{
				return this._tagID;
			}
			set
			{
				if ((this._tagID != value))
				{
					this._tagID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int")]
		public System.Nullable<int> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SpeakerEntity")]
	public partial class SpeakerEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _speakerID;
		
		private string _contactInfo;
		
		private string _description;
		
		private EntitySet<ClassEntity> _ClassEntities;
		
		private EntityRef<EntityItem> _EntityItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnspeakerIDChanging(long value);
    partial void OnspeakerIDChanged();
    partial void OncontactInfoChanging(string value);
    partial void OncontactInfoChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public SpeakerEntity()
		{
			this._ClassEntities = new EntitySet<ClassEntity>(new Action<ClassEntity>(this.attach_ClassEntities), new Action<ClassEntity>(this.detach_ClassEntities));
			this._EntityItem = default(EntityRef<EntityItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speakerID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long speakerID
		{
			get
			{
				return this._speakerID;
			}
			set
			{
				if ((this._speakerID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnspeakerIDChanging(value);
					this.SendPropertyChanging();
					this._speakerID = value;
					this.SendPropertyChanged("speakerID");
					this.OnspeakerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactInfo", DbType="NVarChar(MAX)")]
		public string contactInfo
		{
			get
			{
				return this._contactInfo;
			}
			set
			{
				if ((this._contactInfo != value))
				{
					this.OncontactInfoChanging(value);
					this.SendPropertyChanging();
					this._contactInfo = value;
					this.SendPropertyChanged("contactInfo");
					this.OncontactInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SpeakerEntity_ClassEntity", Storage="_ClassEntities", ThisKey="speakerID", OtherKey="speakerID")]
		public EntitySet<ClassEntity> ClassEntities
		{
			get
			{
				return this._ClassEntities;
			}
			set
			{
				this._ClassEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_SpeakerEntity", Storage="_EntityItem", ThisKey="speakerID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.SpeakerEntity = null;
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.SpeakerEntity = this;
						this._speakerID = value.entityID;
					}
					else
					{
						this._speakerID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ClassEntities(ClassEntity entity)
		{
			this.SendPropertyChanging();
			entity.SpeakerEntity = this;
		}
		
		private void detach_ClassEntities(ClassEntity entity)
		{
			this.SendPropertyChanging();
			entity.SpeakerEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductEntityShipping")]
	public partial class ProductEntityShipping : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _productID;
		
		private int _shippingLocationID;
		
		private EntityRef<ProductEntity> _ProductEntity;
		
		private EntityRef<ShippingLocation> _ShippingLocation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIDChanging(long value);
    partial void OnproductIDChanged();
    partial void OnshippingLocationIDChanging(int value);
    partial void OnshippingLocationIDChanged();
    #endregion
		
		public ProductEntityShipping()
		{
			this._ProductEntity = default(EntityRef<ProductEntity>);
			this._ShippingLocation = default(EntityRef<ShippingLocation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					if (this._ProductEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shippingLocationID", DbType="Int NOT NULL")]
		public int shippingLocationID
		{
			get
			{
				return this._shippingLocationID;
			}
			set
			{
				if ((this._shippingLocationID != value))
				{
					if (this._ShippingLocation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnshippingLocationIDChanging(value);
					this.SendPropertyChanging();
					this._shippingLocationID = value;
					this.SendPropertyChanged("shippingLocationID");
					this.OnshippingLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductEntity_ProductEntityShipping", Storage="_ProductEntity", ThisKey="productID", OtherKey="productID", IsForeignKey=true)]
		public ProductEntity ProductEntity
		{
			get
			{
				return this._ProductEntity.Entity;
			}
			set
			{
				ProductEntity previousValue = this._ProductEntity.Entity;
				if (((previousValue != value) 
							|| (this._ProductEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductEntity.Entity = null;
						previousValue.ProductEntityShipping = null;
					}
					this._ProductEntity.Entity = value;
					if ((value != null))
					{
						value.ProductEntityShipping = this;
						this._productID = value.productID;
					}
					else
					{
						this._productID = default(long);
					}
					this.SendPropertyChanged("ProductEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShippingLocation_ProductEntityShipping", Storage="_ShippingLocation", ThisKey="shippingLocationID", OtherKey="shippingLocationID", IsForeignKey=true)]
		public ShippingLocation ShippingLocation
		{
			get
			{
				return this._ShippingLocation.Entity;
			}
			set
			{
				ShippingLocation previousValue = this._ShippingLocation.Entity;
				if (((previousValue != value) 
							|| (this._ShippingLocation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ShippingLocation.Entity = null;
						previousValue.ProductEntityShippings.Remove(this);
					}
					this._ShippingLocation.Entity = value;
					if ((value != null))
					{
						value.ProductEntityShippings.Add(this);
						this._shippingLocationID = value.shippingLocationID;
					}
					else
					{
						this._shippingLocationID = default(int);
					}
					this.SendPropertyChanged("ShippingLocation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShippingLocation")]
	public partial class ShippingLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _shippingLocationID;
		
		private string _title;
		
		private EntitySet<ProductEntityShipping> _ProductEntityShippings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnshippingLocationIDChanging(int value);
    partial void OnshippingLocationIDChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    #endregion
		
		public ShippingLocation()
		{
			this._ProductEntityShippings = new EntitySet<ProductEntityShipping>(new Action<ProductEntityShipping>(this.attach_ProductEntityShippings), new Action<ProductEntityShipping>(this.detach_ProductEntityShippings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shippingLocationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int shippingLocationID
		{
			get
			{
				return this._shippingLocationID;
			}
			set
			{
				if ((this._shippingLocationID != value))
				{
					this.OnshippingLocationIDChanging(value);
					this.SendPropertyChanging();
					this._shippingLocationID = value;
					this.SendPropertyChanged("shippingLocationID");
					this.OnshippingLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(128)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShippingLocation_ProductEntityShipping", Storage="_ProductEntityShippings", ThisKey="shippingLocationID", OtherKey="shippingLocationID")]
		public EntitySet<ProductEntityShipping> ProductEntityShippings
		{
			get
			{
				return this._ProductEntityShippings;
			}
			set
			{
				this._ProductEntityShippings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProductEntityShippings(ProductEntityShipping entity)
		{
			this.SendPropertyChanging();
			entity.ShippingLocation = this;
		}
		
		private void detach_ProductEntityShippings(ProductEntityShipping entity)
		{
			this.SendPropertyChanging();
			entity.ShippingLocation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileEntity")]
	public partial class FileEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _fileID;
		
		private short _fileTypeID;
		
		private string _filePath;
		
		private string _alternateFilePath;
		
		private EntityRef<EntityItem> _EntityItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfileIDChanging(long value);
    partial void OnfileIDChanged();
    partial void OnfileTypeIDChanging(short value);
    partial void OnfileTypeIDChanged();
    partial void OnfilePathChanging(string value);
    partial void OnfilePathChanged();
    partial void OnalternateFilePathChanging(string value);
    partial void OnalternateFilePathChanged();
    #endregion
		
		public FileEntity()
		{
			this._EntityItem = default(EntityRef<EntityItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long fileID
		{
			get
			{
				return this._fileID;
			}
			set
			{
				if ((this._fileID != value))
				{
					if (this._EntityItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfileIDChanging(value);
					this.SendPropertyChanging();
					this._fileID = value;
					this.SendPropertyChanged("fileID");
					this.OnfileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileTypeID", DbType="SmallInt NOT NULL")]
		public short fileTypeID
		{
			get
			{
				return this._fileTypeID;
			}
			set
			{
				if ((this._fileTypeID != value))
				{
					this.OnfileTypeIDChanging(value);
					this.SendPropertyChanging();
					this._fileTypeID = value;
					this.SendPropertyChanged("fileTypeID");
					this.OnfileTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filePath", DbType="NVarChar(2048)")]
		public string filePath
		{
			get
			{
				return this._filePath;
			}
			set
			{
				if ((this._filePath != value))
				{
					this.OnfilePathChanging(value);
					this.SendPropertyChanging();
					this._filePath = value;
					this.SendPropertyChanged("filePath");
					this.OnfilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alternateFilePath", DbType="NVarChar(2048)")]
		public string alternateFilePath
		{
			get
			{
				return this._alternateFilePath;
			}
			set
			{
				if ((this._alternateFilePath != value))
				{
					this.OnalternateFilePathChanging(value);
					this.SendPropertyChanging();
					this._alternateFilePath = value;
					this.SendPropertyChanged("alternateFilePath");
					this.OnalternateFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EntityItem_FileEntity", Storage="_EntityItem", ThisKey="fileID", OtherKey="entityID", IsForeignKey=true)]
		public EntityItem EntityItem
		{
			get
			{
				return this._EntityItem.Entity;
			}
			set
			{
				EntityItem previousValue = this._EntityItem.Entity;
				if (((previousValue != value) 
							|| (this._EntityItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EntityItem.Entity = null;
						previousValue.FileEntity = null;
					}
					this._EntityItem.Entity = value;
					if ((value != null))
					{
						value.FileEntity = this;
						this._fileID = value.entityID;
					}
					else
					{
						this._fileID = default(long);
					}
					this.SendPropertyChanged("EntityItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubscribePlanXref")]
	public partial class SubscribePlanXref : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _subscribePlanID;
		
		private long _nextSubscribePlanID;
		
		private System.Nullable<int> _freeUnitsOnNextSubscribe;
		
		private EntityRef<SubscribePlanEntity> _SubscribePlanEntity;
		
		private EntityRef<SubscribePlanEntity> _SubscribePlanEntity1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsubscribePlanIDChanging(long value);
    partial void OnsubscribePlanIDChanged();
    partial void OnnextSubscribePlanIDChanging(long value);
    partial void OnnextSubscribePlanIDChanged();
    partial void OnfreeUnitsOnNextSubscribeChanging(System.Nullable<int> value);
    partial void OnfreeUnitsOnNextSubscribeChanged();
    #endregion
		
		public SubscribePlanXref()
		{
			this._SubscribePlanEntity = default(EntityRef<SubscribePlanEntity>);
			this._SubscribePlanEntity1 = default(EntityRef<SubscribePlanEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subscribePlanID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long subscribePlanID
		{
			get
			{
				return this._subscribePlanID;
			}
			set
			{
				if ((this._subscribePlanID != value))
				{
					if (this._SubscribePlanEntity1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsubscribePlanIDChanging(value);
					this.SendPropertyChanging();
					this._subscribePlanID = value;
					this.SendPropertyChanged("subscribePlanID");
					this.OnsubscribePlanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nextSubscribePlanID", DbType="BigInt NOT NULL")]
		public long nextSubscribePlanID
		{
			get
			{
				return this._nextSubscribePlanID;
			}
			set
			{
				if ((this._nextSubscribePlanID != value))
				{
					if (this._SubscribePlanEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnextSubscribePlanIDChanging(value);
					this.SendPropertyChanging();
					this._nextSubscribePlanID = value;
					this.SendPropertyChanged("nextSubscribePlanID");
					this.OnnextSubscribePlanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeUnitsOnNextSubscribe", DbType="Int")]
		public System.Nullable<int> freeUnitsOnNextSubscribe
		{
			get
			{
				return this._freeUnitsOnNextSubscribe;
			}
			set
			{
				if ((this._freeUnitsOnNextSubscribe != value))
				{
					this.OnfreeUnitsOnNextSubscribeChanging(value);
					this.SendPropertyChanging();
					this._freeUnitsOnNextSubscribe = value;
					this.SendPropertyChanged("freeUnitsOnNextSubscribe");
					this.OnfreeUnitsOnNextSubscribeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubscribePlanEntity_SubscribePlanXref", Storage="_SubscribePlanEntity", ThisKey="nextSubscribePlanID", OtherKey="subscribePlanID", IsForeignKey=true)]
		public SubscribePlanEntity SubscribePlanEntity
		{
			get
			{
				return this._SubscribePlanEntity.Entity;
			}
			set
			{
				SubscribePlanEntity previousValue = this._SubscribePlanEntity.Entity;
				if (((previousValue != value) 
							|| (this._SubscribePlanEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SubscribePlanEntity.Entity = null;
						previousValue.SubscribePlanXrefs.Remove(this);
					}
					this._SubscribePlanEntity.Entity = value;
					if ((value != null))
					{
						value.SubscribePlanXrefs.Add(this);
						this._nextSubscribePlanID = value.subscribePlanID;
					}
					else
					{
						this._nextSubscribePlanID = default(long);
					}
					this.SendPropertyChanged("SubscribePlanEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SubscribePlanEntity_SubscribePlanXref1", Storage="_SubscribePlanEntity1", ThisKey="subscribePlanID", OtherKey="subscribePlanID", IsForeignKey=true)]
		public SubscribePlanEntity SubscribePlanEntity1
		{
			get
			{
				return this._SubscribePlanEntity1.Entity;
			}
			set
			{
				SubscribePlanEntity previousValue = this._SubscribePlanEntity1.Entity;
				if (((previousValue != value) 
							|| (this._SubscribePlanEntity1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SubscribePlanEntity1.Entity = null;
						previousValue.SubscribePlanXref = null;
					}
					this._SubscribePlanEntity1.Entity = value;
					if ((value != null))
					{
						value.SubscribePlanXref = this;
						this._subscribePlanID = value.subscribePlanID;
					}
					else
					{
						this._subscribePlanID = default(long);
					}
					this.SendPropertyChanged("SubscribePlanEntity1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
