<?xml version="1.0" encoding="utf-8"?><Database Name="Aisha" EntityNamespace="MainEntity.Models.Entity" Class="EntityItemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ts;Initial Catalog=Aisha;Persist Security Info=True;User ID=aisha" SettingsObjectName="MainEntity.Properties.Settings" SettingsPropertyName="AishaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EntityItem" Member="EntityItems">
    <Type Name="EntityItem">
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rootEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="parentEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="creatorID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="hierarchiID" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="sortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EntityItem_FileEntity" Member="FileEntity" ThisKey="entityID" OtherKey="fileID" Type="FileEntity" Cardinality="One" />
      <Association Name="EntityType_EntityItem" Member="EntityType" ThisKey="typeID" OtherKey="typeID" Type="EntityType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EntityType" Member="EntityTypes">
    <Type Name="EntityType">
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="EntityType_EntityItem" Member="EntityItems" ThisKey="typeID" OtherKey="typeID" Type="EntityItem" />
    </Type>
  </Table>
  <Table Name="dbo.FileEntity" Member="FileEntities">
    <Type Name="FileEntity">
      <Column Name="fileID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fileTypeID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="filePath" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="alternateFilePath" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Association Name="EntityItem_FileEntity" Member="EntityItem" ThisKey="fileID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
</Database>