<?xml version="1.0" encoding="utf-8"?><Database Name="Aisha_real" EntityNamespace="MainEntity.Models.Portal" Class="PortalEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ts;Initial Catalog=Aisha_real;Persist Security Info=True;User ID=aisha" SettingsObjectName="MainEntity.Properties.Settings" SettingsPropertyName="Aisha_realConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EntityItem" Member="EntityItems">
    <Type Name="EntityItem">
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rootEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="parentEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="creatorID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="hierarchiID" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="sortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EntityItem_PortalAlias" Member="PortalAlias" ThisKey="entityID" OtherKey="portalID" Type="PortalAlias" />
      <Association Name="EntityItem_PortalEntity" Member="PortalEntity" ThisKey="entityID" OtherKey="portalID" Type="PortalEntity" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.PortalAlias" Member="PortalAlias">
    <Type Name="PortalAlias">
      <Column Name="portalAliasID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="portalID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="alias" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="EntityItem_PortalAlias" Member="EntityItem" ThisKey="portalID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
      <Association Name="PortalEntity_PortalAlias" Member="PortalEntity" ThisKey="portalID" OtherKey="portalID" Type="PortalEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortalUser" Member="PortalUsers">
    <Type Name="PortalUser">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="portalID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PortalEntity_PortalUser" Member="PortalEntity" ThisKey="portalID" OtherKey="portalID" Type="PortalEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PortalEntity" Member="PortalEntities">
    <Type Name="PortalEntity">
      <Column Name="portalID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="themeName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="applicationName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="authorizedOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="allowBuyFiles" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="allowBuyProducts" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="allowRegister" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="allowAuthorize" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="passwordProtection" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="PortalEntity_PortalAlias" Member="PortalAlias" ThisKey="portalID" OtherKey="portalID" Type="PortalAlias" />
      <Association Name="PortalEntity_PortalUser" Member="PortalUsers" ThisKey="portalID" OtherKey="portalID" Type="PortalUser" />
      <Association Name="EntityItem_PortalEntity" Member="EntityItem" ThisKey="portalID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
</Database>