<?xml version="1.0" encoding="utf-8"?><Database Name="Aisha_real" EntityNamespace="MainEntity.Models.Shopping" Class="ShoppingEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ts;Initial Catalog=Aisha_real;Persist Security Info=True;User ID=aisha" SettingsObjectName="MainEntity.Properties.Settings" SettingsPropertyName="Aisha_realConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SubscribePlanEntity" Member="SubscribePlanEntities">
    <Type Name="SubscribePlanEntity">
      <Column Name="subscribePlanID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="durationInDays" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="durationInMonths" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="freeUnitsOnSubscribe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="freeOfferCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Association Name="SubscribePlanEntity_MembershipXrefSubscribePlan" Member="MembershipXrefSubscribePlans" ThisKey="subscribePlanID" OtherKey="subscribePlanID" Type="MembershipXrefSubscribePlan" />
      <Association Name="EntityItem_SubscribePlanEntity" Member="EntityItem" ThisKey="subscribePlanID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Membership" Member="Memberships">
    <Type Name="Membership">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activatedCart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="activationCartDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="balance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="freeOfferCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="refferedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="postalCode" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="postalAdderss" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="dayPhone" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="subscribeActivation" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="chargeDay" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="suspended" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fullLibraryAccess" Storage="_fullLibraryAccess" Type="System.Boolean" DbType="Bit NO NULL" CanBeNull="false" />
      <Association Name="Membership_MembershipXrefSubscribePlan" Member="MembershipXrefSubscribePlan" ThisKey="UserId" OtherKey="UserId" Type="MembershipXrefSubscribePlan" Cardinality="One" />
      <Association Name="Membership_MembershipAddress" Member="MembershipAddresses" ThisKey="UserId" OtherKey="UserId" Type="MembershipAddress" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingLog" Member="ShoppingLogs">
    <Type Name="ShoppingLog">
      <Column Name="shoppingLogID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="shoppingID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="shoppingStateID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingState_ShoppingLog" Member="ShoppingState" ThisKey="shoppingStateID" OtherKey="shoppingStateID" Type="ShoppingState" IsForeignKey="true" />
      <Association Name="Shopping_ShoppingLog" Member="Shopping" ThisKey="shoppingID" OtherKey="shoppingID" Type="Shopping" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MembershipXrefSubscribePlan" Member="MembershipXrefSubscribePlans">
    <Type Name="MembershipXrefSubscribePlan">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="subscribePlanID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="startSubscribeDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="endSubscribeDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="cancelSubscribe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="activationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="declineSubscribe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SubscribePlanEntity_MembershipXrefSubscribePlan" Member="SubscribePlanEntity" ThisKey="subscribePlanID" OtherKey="subscribePlanID" Type="SubscribePlanEntity" IsForeignKey="true" />
      <Association Name="Membership_MembershipXrefSubscribePlan" Member="Membership" ThisKey="UserId" OtherKey="UserId" Type="Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductEntity" Member="ProductEntities">
    <Type Name="ProductEntity">
      <Column Name="productID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="productTypeID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="price1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="price2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="unlimitedAccessInLibrary" Storage="_unlimitedAccessInLibrary" Type="System.Boolean" DbType="Bit NO NULL" CanBeNull="false" />
      <Association Name="ProductEntity_ProductXrefEntity" Member="ProductXrefEntities" ThisKey="productID" OtherKey="productID" Type="ProductXrefEntity" />
      <Association Name="EntityItem_ProductEntity" Member="EntityItem" ThisKey="productID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
      <Association Name="ProductType_ProductEntity" Member="ProductType" ThisKey="productTypeID" OtherKey="productTypeID" Type="ProductType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EntityItem" Member="EntityItems">
    <Type Name="EntityItem">
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rootEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="parentEntityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="creatorID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="hierarchiID" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="sortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EntityItem_SubscribePlanEntity" Member="SubscribePlanEntity" ThisKey="entityID" OtherKey="subscribePlanID" Type="SubscribePlanEntity" Cardinality="One" />
      <Association Name="EntityItem_ProductEntity" Member="ProductEntity" ThisKey="entityID" OtherKey="productID" Type="ProductEntity" Cardinality="One" />
      <Association Name="EntityItem_ProductXrefEntity" Member="ProductXrefEntities" ThisKey="entityID" OtherKey="entityID" Type="ProductXrefEntity" />
      <Association Name="EntityItem_Shopping" Member="Shoppings" ThisKey="entityID" OtherKey="entityID" Type="Shopping" />
      <Association Name="EntityItem_ClassEntity" Member="ClassEntity" ThisKey="entityID" OtherKey="classID" Type="ClassEntity" Cardinality="One" />
      <Association Name="EntityItem_SpeakerEntity" Member="SpeakerEntity" ThisKey="entityID" OtherKey="speakerID" Type="SpeakerEntity" Cardinality="One" />
      <Association Name="EntityItem_CatalogItemExtend" Member="CatalogItemExtend" ThisKey="entityID" OtherKey="entityID" Type="CatalogItemExtend" Cardinality="One" />
      <Association Name="EntityType_EntityItem" Member="EntityType" ThisKey="typeID" OtherKey="typeID" Type="EntityType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductXrefEntity" Member="ProductXrefEntities">
    <Type Name="ProductXrefEntity">
      <Column Name="productID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="EntityItem_ProductXrefEntity" Member="EntityItem" ThisKey="entityID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
      <Association Name="ProductEntity_ProductXrefEntity" Member="ProductEntity" ThisKey="productID" OtherKey="productID" Type="ProductEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingMembershipAddress" Member="ShoppingMembershipAddresses">
    <Type Name="ShoppingMembershipAddress">
      <Column Name="shoppingTransactionID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="addressID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingTransaction_ShoppingMembershipAddress" Member="ShoppingTransaction" ThisKey="shoppingTransactionID" OtherKey="shoppingTransactionID" Type="ShoppingTransaction" IsForeignKey="true" />
      <Association Name="MembershipAddress_ShoppingMembershipAddress" Member="MembershipAddress" ThisKey="addressID" OtherKey="addressID" Type="MembershipAddress" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingState" Member="ShoppingStates">
    <Type Name="ShoppingState">
      <Column Name="shoppingStateID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingState_ShoppingLog" Member="ShoppingLogs" ThisKey="shoppingStateID" OtherKey="shoppingStateID" Type="ShoppingLog" />
      <Association Name="ShoppingState_Shopping" Member="Shoppings" ThisKey="shoppingStateID" OtherKey="shoppingStateID" Type="Shopping" />
    </Type>
  </Table>
  <Table Name="dbo.EntityType" Member="EntityTypes">
    <Type Name="EntityType">
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="EntityType_EntityItem" Member="EntityItems" ThisKey="typeID" OtherKey="typeID" Type="EntityItem" />
    </Type>
  </Table>
  <Table Name="dbo.Shopping" Member="Shoppings">
    <Type Name="Shopping">
      <Column Name="shoppingID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="shoppingStateID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="shoppingTransactionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="price1" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="price2" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="[count]" Member="cnt" Storage="_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unlimitedAccessInLibrary" Storage="_unlimitedAccessInLibrary" Type="System.Boolean" DbType="Bit NO NULL" CanBeNull="false" />
      <Association Name="Shopping_ShoppingLog" Member="ShoppingLogs" ThisKey="shoppingID" OtherKey="shoppingID" Type="ShoppingLog" />
      <Association Name="EntityItem_Shopping" Member="EntityItem" ThisKey="entityID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
      <Association Name="ShoppingState_Shopping" Member="ShoppingState" ThisKey="shoppingStateID" OtherKey="shoppingStateID" Type="ShoppingState" IsForeignKey="true" />
      <Association Name="ShoppingTransaction_Shopping" Member="ShoppingTransaction" ThisKey="shoppingTransactionID" OtherKey="shoppingTransactionID" Type="ShoppingTransaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductType" Member="ProductTypes">
    <Type Name="ProductType">
      <Column Name="productTypeID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="ProductType_ProductEntity" Member="ProductEntities" ThisKey="productTypeID" OtherKey="productTypeID" Type="ProductEntity" />
    </Type>
  </Table>
  <Table Name="dbo.ClassEntity" Member="ClassEntities">
    <Type Name="ClassEntity">
      <Column Name="classID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="speakerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="duration" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="statDownloadCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statListenCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EntityItem_ClassEntity" Member="EntityItem" ThisKey="classID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
      <Association Name="SpeakerEntity_ClassEntity" Member="SpeakerEntity" ThisKey="speakerID" OtherKey="speakerID" Type="SpeakerEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SpeakerEntity" Member="SpeakerEntities">
    <Type Name="SpeakerEntity">
      <Column Name="speakerID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contactInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="SpeakerEntity_ClassEntity" Member="ClassEntities" ThisKey="speakerID" OtherKey="speakerID" Type="ClassEntity" />
      <Association Name="EntityItem_SpeakerEntity" Member="EntityItem" ThisKey="speakerID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CatalogItemExtend" Member="CatalogItemExtends">
    <Type Name="CatalogItemExtend">
      <Column Name="entityID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="EntityItem_CatalogItemExtend" Member="EntityItem" ThisKey="entityID" OtherKey="entityID" Type="EntityItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ShoppingClass" Member="ShoppingClasses">
    <Type Name="ShoppingClass">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="shoppingStateID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="speakerName" Type="System.String" DbType="NVarChar(450) NOT NULL" CanBeNull="false" />
      <Column Name="fileID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="classID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="unlimitedAccessInLibrary" Storage="_unlimitedAccessInLibrary" Type="System.Boolean" DbType="Bit NO NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingCartPayment" Member="ShoppingCartPayments">
    <Type Name="ShoppingCartPayment">
      <Column Name="shoppingTransactionID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="membershipCartID" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingTransaction_ShoppingCartPayment" Member="ShoppingTransaction" ThisKey="shoppingTransactionID" OtherKey="shoppingTransactionID" Type="ShoppingTransaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingTransaction" Member="ShoppingTransactions">
    <Type Name="ShoppingTransaction">
      <Column Name="shoppingTransactionID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="holdBalance" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="tranID" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="chargetype" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="transactionState" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="response" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Association Name="ShoppingTransaction_ShoppingMembershipAddress" Member="ShoppingMembershipAddress" ThisKey="shoppingTransactionID" OtherKey="shoppingTransactionID" Type="ShoppingMembershipAddress" Cardinality="One" />
      <Association Name="ShoppingTransaction_Shopping" Member="Shoppings" ThisKey="shoppingTransactionID" OtherKey="shoppingTransactionID" Type="Shopping" />
      <Association Name="ShoppingTransaction_ShoppingCartPayment" Member="ShoppingCartPayment" ThisKey="shoppingTransactionID" OtherKey="shoppingTransactionID" Type="ShoppingCartPayment" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ShoppingTransaction" Member="UserShoppingTransactions">
    <Type Name="UserShoppingTransaction">
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="shoppingTransactionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="tranID" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="membershipCartID" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="cartStateID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="expirationDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="cartTypeID" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="cartTranID" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="response" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="chargetype" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="transactionState" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MembershipAddress" Member="MembershipAddresses">
    <Type Name="MembershipAddress">
      <Column Name="addressID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="isBillingAddress" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="postalCode" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="postalAdderss" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="dayPhone" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="MembershipAddress_ShoppingMembershipAddress" Member="ShoppingMembershipAddresses" ThisKey="addressID" OtherKey="addressID" Type="ShoppingMembershipAddress" />
      <Association Name="Membership_MembershipAddress" Member="Membership" ThisKey="UserId" OtherKey="UserId" Type="Membership" IsForeignKey="true" />
    </Type>
  </Table>
</Database>